// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkX_6CbWcKeqbLUJJCUp2Llc9uJUumQeg',
    appId: '1:955899718417:android:f4c57263f7731ab28bfab0',
    messagingSenderId: '955899718417',
    projectId: 'gotourrd',
    storageBucket: 'gotourrd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWWzw2x0Y7EP3KUMnpim3aVdpLJ4B6UEk',
    appId: '1:955899718417:ios:e8330efd2a219eb68bfab0',
    messagingSenderId: '955899718417',
    projectId: 'gotourrd',
    storageBucket: 'gotourrd.appspot.com',
    androidClientId: '955899718417-1v6h5ih5eve4ln2av629fatu6uo78cbh.apps.googleusercontent.com',
    iosClientId: '955899718417-ilbm27mg5voeis04n477htl8t1ms2ivh.apps.googleusercontent.com',
    iosBundleId: 'com.example.designerdigger',
  );
}
